kafka:
  brokers: kafka-365d19e0-ryan-0df0.aivencloud.com:11584
  topic: testtopic
  message_key: message
  offset_reset: latest
  group_id: testgroup
  ssl_cafile: ca.pem
  ssl_certfile: service.cert
  ssl_keyfile: service.key

postgres:
  host: <hidden>.aivencloud.com
  port: 11582
  database: testdb
  user: testuser
  password: <hidden>
  table: testtable
  column: message
